api:
  resource: '.'
  type:     'api_platform'

app:
  resource: '@AppBundle/Action/'
  type:     'annotation'

api_login_check:
  path: /login

_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"
